version: 2.1

orbs:
  ruby: circleci/ruby@1.0

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.1-browsers
    parallelism: 4
    steps:
      - checkout
      - run: 
          name: Bundle install
          command: bundle install --path vendor/bundle
      - ruby/install-deps
      - run: 
          name: Execute all features scenarios
          command: bundle exec cucumber 
      - store_test_results:
          path: log/report.html
      - store_artifacts:
          path: log/report.html 